name: Build and Deploy Packer Image

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: cloud
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run Tests
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
        run: npm test

      - name: Create `webapp.zip`
        run: |
          zip -r webapp.zip .

      - name: Upload `webapp.zip` as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: webapp.zip


  build-and-deploy:
    needs: test-and-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download `webapp.zip` Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact
          path: /tmp

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v0.2.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

          
      - name: Set Google Cloud Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | gcloud auth activate-service-account --key-file=-
          
      # Verify the setup by checking the active project and authentication
      - name: Check Google Cloud Auth
        run: gcloud auth list
      
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: '>=1.0.0, <2.0.0' 

      - name: Initialize Packer
        run: |
          packer init packer/variables.pkr.hcl

      - name: Validate Packer Template
        run: |
          packer validate packer/variables.pkr.hcl

      - name: Run Packer Build
        run: |
          packer build -var "artifact_path=/tmp/webapp.zip" packer/variables.pkr.hcl
